### ISSUE TITLE
get_library order of search filters seems to be problematic

### ISSUE THREAD

**Issue by OzGav** [music-assistant/backlog#10]
Also reported here https://github.com/music-assistant/support/issues/3943

I think a similar query has been resolved but I can’t find it now….in short I think the following action is doing the favourite only filter at the end of the search which results often in no results. If what is happening is what I think is happening then the library should be filtered for favourites first and then the list randomised and then the limit applied 

```
action: music_assistant.get_library
data:
  limit: 1
  offset: 0
  album_artists_only: false
  config_entry_id: 01JMYCMQJ55CR9E7YZW3VKEA4F
  media_type: track
  order_by: random
  favorite: true

```

Ultimately the goal is to be able to return a single track from all the songs that are favourited so if there is a better way to do that than the above I am all ears.

I think overall I would expect the get_library action to work as follows:

First, grab all items from the library that have the specified media type
Next, (I don’t think order of these would matter), filter by: `favourite`, `search term`, `album artist`, and then `album type`(if applicable)
Next, Apply the offset 
Next, Apply the limit
Last, Order the results as selected
